### ISSUE TITLE
Big Thumbnail display is created from ... lower res thumbnails, not original?

### ISSUE THREAD

**Issue by shakeyourbunny** [Lacro59/playnite-screenshotsvisualizer-plugin#3]
Hello,

big thumbnails are generated now with 1.2.1 from the lower resolution thumbnails? This is a regression.

still a bug: screenshot strip is not updating and highlight current image which has been clicked on the forward / backwards button.

See also
https://www.youtube.com/watch?v=UKS43Yh9uqk

I also noticed that, if you use the screenshot popup, the inital state is that no picture has been selected (default: first one or last one clicked).

**Comment by Lacro59** [comment]
I had planned to improve it and adjust the resolution for thumbnails size.
