### ISSUE TITLE
[Bug] Paths with two concatenated spaces are not being detected

### ISSUE THREAD

**Issue by BanCrash** [Lacro59/playnite-screenshotsvisualizer-plugin#64]
EDIT: Lol, it seems that GitHub removes the extra space. There is two spaces between "edge" and "Catalyst" instead only one. The same happens for "Test" and "2"

Hi, I tried to use the automatically created by Nvidia GForce Experience folder of Mirror's edge Catalyst, and I've found that folders with two spaces on their title are not being detected:

I've tried with the original folder, which is "Mirror's Edge  Catalyst", and the log says: 16-10 21:00:36.409|WARN |ScreenshotsVisualizer#PluginDatabaseObject`4:Screenshots directory not found for Mirror's Edge Catalyst

However, if I rename the folder to "Mirror's Edge Catalyst" it works as expected.

After that, I created a folder named "Test  2", and also it's not being detected, so it seems that for some reason when the folder have two concatenated spaces the plugin will fail to detect it.

EDIT 2:

![imagen](https://user-images.githubusercontent.com/11770760/196053521-4de58b31-6956-4e5c-9351-d31563213ff1.png)

First folder is not working while second is, even when both folders are created and have files inside.

**Comment by Lacro59** [comment]
fixed with last release

**Comment by BanCrash** [comment]
Perfect, thank you again Lacro59 !
