### ISSUE TITLE
it doesn't import screenshots. 

### ISSUE THREAD

**Issue by triadne** [Lacro59/playnite-screenshotsvisualizer-plugin#74]
there is no button to 'refresh data' except for in each game's individual menu. I have hundreds of games, so it's not feasible for me to go through each one refreshing data. surely there must be something not quite working and either it's supposed to do it automatically, or there is some UI element missing that I'm supposed to click to get it to scan my folders?

**Comment by Lacro59** [comment]
![image](https://github.com/Lacro59/playnite-screenshotsvisualizer-plugin/assets/124054/232ced70-1740-461f-ba97-0a1f4a0962a8)
